--liquibase formatted sql

-- ChangeSet petr.havelka:1
DROP TABLE povrch IF EXISTS;
CREATE TABLE povrch (
  id            int GENERATED BY DEFAULT AS IDENTITY, 
  nazev         nvarchar(100) NOT NULL, 
  cena          decimal(16, 2) NOT NULL, 
  zmenacas      timestamp DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
  zmenauzivatel nvarchar(20) NOT NULL, 
  platnost      int DEFAULT 1 NOT NULL, 
  PRIMARY KEY (id));

DROP TABLE zakaznik IF EXISTS;
CREATE TABLE zakaznik (
  id            int GENERATED BY DEFAULT AS IDENTITY, 
  telefon       nchar(9) NOT NULL UNIQUE, 
  celejmeno     nvarchar(100) NOT NULL, 
  zmenacas      timestamp DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
  zmenauzivatel nvarchar(20) NOT NULL, 
  platnost      int DEFAULT 1 NOT NULL, 
  PRIMARY KEY (id));
CREATE UNIQUE INDEX zakaznik_telefon 
  ON zakaznik (telefon);
  
DROP TABLE kurt IF EXISTS;
CREATE TABLE kurt (
  id            int GENERATED BY DEFAULT AS IDENTITY, 
  refpovrch     int NOT NULL, 
  nazev         nvarchar(100) NOT NULL, 
  zmenacas      timestamp DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
  zmenauzivatel nvarchar(20) NOT NULL, 
  platnost      int DEFAULT 1 NOT NULL, 
  PRIMARY KEY (id));
ALTER TABLE kurt ADD CONSTRAINT FKkurt553117 FOREIGN KEY (refpovrch) REFERENCES povrch (id);

DROP TABLE rezervace IF EXISTS;
CREATE TABLE rezervace (
  id            int GENERATED BY DEFAULT AS IDENTITY, 
  refkurt       int NOT NULL, 
  refzakaznik   int NOT NULL, 
  datumod       datetime NOT NULL, 
  datumdo       datetime NOT NULL, 
  ctyrhra       int DEFAULT 0 NOT NULL,
  cenapronajem  decimal(16, 2) NOT NULL, 
  zmenacas      timestamp DEFAULT CURRENT_TIMESTAMP() NOT NULL, 
  zmenauzivatel nvarchar(20) NOT NULL, 
  platnost      int DEFAULT 1 NOT NULL, 
  PRIMARY KEY (id));
ALTER TABLE rezervace ADD CONSTRAINT FKrezervace102341 FOREIGN KEY (refkurt) REFERENCES kurt (id);
ALTER TABLE rezervace ADD CONSTRAINT FKrezervace69195 FOREIGN KEY (refzakaznik) REFERENCES zakaznik (id);
  